// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//! pcap-fixture conformance — decodes the checked-in
//! `tests/fixtures/rtps_go_dds_reference.pcap` (regenerated by
//! `examples/generate_rtps_pcap_fixture.rs`; see that file's doc comment
//! for exactly where each recorded message's bytes come from and the
//! go-DDS reproduction command behind each one) and checks every recorded
//! RTPS message byte-for-byte *and* via this crate's own decode path
//! (`Header::decode` + `SubmessageIter` + the per-submessage `decode_*`
//! functions), so a regression in either this crate's pcap container
//! handling or its RTPS decode path is caught here — no live peer process,
//! no network I/O, deterministic, runs in the default `cargo test` sweep.
//!
//! ROADMAP.md, "Interop testing" section, deliverable 2 of 3
//! ("pcap-fixture conformance").
//!
//! To regenerate the fixture after an intentional wire-format change:
//!
//! ```text
//! cargo run --example generate_rtps_pcap_fixture > tests/fixtures/rtps_go_dds_reference.pcap
//! ```

use rust_dds::rtps::guid::{
    entity_id_for_reader, entity_id_for_writer, ENTITYID_SEDP_PUB_WRITER, ENTITYID_SEDP_SUB_WRITER,
    ENTITYID_SPDP_WRITER, ENTITYID_UNKNOWN,
};
use rust_dds::rtps::message::{
    decode_acknack_submessage, decode_data_submessage, decode_heartbeat_submessage, Header,
    RawSubmessage, SubmessageIter, SUBMSG_ACKNACK, SUBMSG_DATA, SUBMSG_GAP, SUBMSG_HEARTBEAT,
};
use rust_dds::rtps::pcap::decode_pcap_file;

const FIXTURE_BYTES: &[u8] = include_bytes!("fixtures/rtps_go_dds_reference.pcap");

fn only_submessage(body: &[u8]) -> RawSubmessage<'_> {
    let mut iter = SubmessageIter::new(body);
    let first = iter
        .next()
        .expect("no submessage decoded")
        .expect("submessage decode error");
    assert!(iter.next().is_none(), "expected exactly one submessage");
    first
}

#[test]
fn fixture_has_exactly_the_seven_expected_recorded_messages_in_order() {
    let packets = decode_pcap_file(FIXTURE_BYTES).expect("valid pcap file");
    assert_eq!(packets.len(), 7);
    for pkt in &packets {
        assert_eq!(
            &pkt.payload[0..4],
            b"RTPS",
            "every recorded message starts with the RTPS magic"
        );
    }
}

#[test]
fn spdp_announcement_decodes_and_matches_go_dds_reference_bytes() {
    let packets = decode_pcap_file(FIXTURE_BYTES).unwrap();
    let msg = &packets[0].payload;
    assert_eq!(
        hex::encode(msg),
        "52545053020301270102030405060708090a0b0c15058c0000001000000100c7000100c200000000010000000300000015000400020300001600040001270000500010000102030405060708090a0b0c000001c1580004003f000000320018000100000002440000000000000000000000000000000000002f001800010000000344000000000000000000000000000000000000020008000a0000000000000001000000"
    );

    let header = Header::decode(msg).unwrap();
    assert_eq!(
        header.guid_prefix.0,
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    );
    let submsg = only_submessage(&msg[Header::LEN..]);
    assert_eq!(submsg.id, SUBMSG_DATA);
    let ds = decode_data_submessage(submsg.flags, submsg.body).unwrap();
    assert_eq!(ds.writer_entity_id, ENTITYID_SPDP_WRITER);
    assert_eq!(ds.seq_num.to_u64(), 1);
    assert_eq!(ds.payload.as_ref().unwrap().len(), 120);
}

#[test]
fn sedp_publication_announcement_decodes_and_matches_go_dds_reference_bytes() {
    let packets = decode_pcap_file(FIXTURE_BYTES).unwrap();
    let msg = &packets[1].payload;
    assert_eq!(
        hex::encode(msg),
        "52545053020301270102030405060708090a0b0c1505700000001000000003c7000003c20000000001000000030000005a0010000102030405060708090a0b0c0000010305000c0007000000537175617265000007001000090000004344525f424c4f42000000002f00180001000000034400000000000000000000000000000000000001000000"
    );

    let submsg = only_submessage(&msg[Header::LEN..]);
    assert_eq!(submsg.id, SUBMSG_DATA);
    let ds = decode_data_submessage(submsg.flags, submsg.body).unwrap();
    assert_eq!(ds.writer_entity_id, ENTITYID_SEDP_PUB_WRITER);
    let payload = ds.payload.unwrap();
    assert_eq!(payload.len(), 92);
}

#[test]
fn sedp_subscription_announcement_decodes_with_reader_entity_and_matches_go_dds_reference_bytes() {
    let packets = decode_pcap_file(FIXTURE_BYTES).unwrap();
    let msg = &packets[2].payload;
    assert_eq!(
        hex::encode(msg),
        "52545053020301270102030405060708090a0b0c1505700000001000000004c7000004c20000000001000000030000005a\
0010000102030405060708090a0b0c0000010405000c0007000000537175617265000007001000090000004344525f424c4f4200\
0000002f00180001000000034400000000000000000000000000000000000001000000"
    );

    let submsg = only_submessage(&msg[Header::LEN..]);
    assert_eq!(submsg.id, SUBMSG_DATA);
    let ds = decode_data_submessage(submsg.flags, submsg.body).unwrap();
    assert_eq!(ds.writer_entity_id, ENTITYID_SEDP_SUB_WRITER);
}

#[test]
fn plain_data_submessage_decodes_and_matches_go_dds_reference_bytes() {
    let packets = decode_pcap_file(FIXTURE_BYTES).unwrap();
    let msg = &packets[3].payload;
    assert_eq!(
        hex::encode(msg),
        "52545053020301270102030405060708090a0b0c15051e00000010000000000000000103000000000100000001000000deadbeef0102"
    );

    let submsg = only_submessage(&msg[Header::LEN..]);
    assert_eq!(submsg.id, SUBMSG_DATA);
    let ds = decode_data_submessage(submsg.flags, submsg.body).unwrap();
    assert_eq!(ds.writer_entity_id, entity_id_for_writer(1));
    assert_eq!(ds.reader_entity_id, ENTITYID_UNKNOWN);
    assert_eq!(ds.seq_num.to_u64(), 1);
    let wrapped = ds.payload.unwrap();
    let unwrapped = rust_dds::rtps::cdr::unwrap_payload(&wrapped).unwrap();
    assert_eq!(unwrapped, [0xDE, 0xAD, 0xBE, 0xEF, 0x01, 0x02]);
}

#[test]
fn heartbeat_decodes_and_matches_go_dds_reference_bytes() {
    let packets = decode_pcap_file(FIXTURE_BYTES).unwrap();
    let msg = &packets[4].payload;
    let submsg = only_submessage(&msg[Header::LEN..]);
    assert_eq!(submsg.id, SUBMSG_HEARTBEAT);
    // Submessage body bytes (header + body) match message.rs's own
    // go-DDS-verified reference exactly.
    assert_eq!(
        hex::encode(&msg[Header::LEN..]),
        "07011c0000000000000001030000000001000000000000000500000003000000"
    );
    let hb = decode_heartbeat_submessage(submsg.body).unwrap();
    assert_eq!(hb.writer_entity_id, entity_id_for_writer(1));
    assert_eq!(hb.first_sn.to_u64(), 1);
    assert_eq!(hb.last_sn.to_u64(), 5);
    assert_eq!(hb.count, 3);
}

#[test]
fn acknack_decodes_and_matches_go_dds_reference_bytes() {
    let packets = decode_pcap_file(FIXTURE_BYTES).unwrap();
    let msg = &packets[5].payload;
    let submsg = only_submessage(&msg[Header::LEN..]);
    assert_eq!(submsg.id, SUBMSG_ACKNACK);
    assert_eq!(
        hex::encode(&msg[Header::LEN..]),
        "06011c0000000204000001030000000003000000200000000500000007000000"
    );
    let an = decode_acknack_submessage(submsg.body).unwrap();
    assert_eq!(an.reader_entity_id, entity_id_for_reader(2));
    assert_eq!(an.writer_entity_id, entity_id_for_writer(1));
    assert_eq!(an.base.to_u64(), 3);
    assert_eq!(an.bitmap, 0b101);
    assert_eq!(an.count, 7);
}

#[test]
fn gap_submessage_is_present_and_matches_go_dds_reference_bytes() {
    // go-DDS never parses a GAP it receives (see message.rs's own module
    // docs — "Encode-only ... no `parseGAP`/`submsgGAP` case exists in
    // go-DDS's own `handleDataPacket`"), so this crate has no
    // `decode_gap_submessage` to call either; this test checks the
    // recorded bytes and submessage framing only, matching the crate's
    // own encode-only scope for GAP.
    let packets = decode_pcap_file(FIXTURE_BYTES).unwrap();
    let msg = &packets[6].payload;
    let submsg = only_submessage(&msg[Header::LEN..]);
    assert_eq!(submsg.id, SUBMSG_GAP);
    assert_eq!(
        hex::encode(&msg[Header::LEN..]),
        "08011c0000000204000001030000000001000000000000000500000000000000"
    );
}
