// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//! pcap-fixture conformance — the second of the three interop-testing
//! deliverables in `ROADMAP.md`'s "Interop testing" section (after the
//! live two-process harness in `tests/rtps_two_process_interop.rs`, which
//! this module has no runtime dependency on).
//!
//! Pure encode/decode for the standard libpcap "classic" file format
//! (global header + per-record headers, as read by `tcpdump -r`/Wireshark)
//! wrapping IPv4/UDP-framed RTPS messages, no I/O — same idiom as `cdr.rs`/
//! `message.rs`. The point of a *pcap* fixture specifically (rather than a
//! bare hex/binary blob of RTPS bytes, which every other sub-phase's
//! `tests` module already checks in as literals) is that the checked-in
//! fixture file this module's tests read
//! (`tests/fixtures/rtps_go_dds_reference.pcap`) is a real, valid capture
//! file — openable in Wireshark or `tcpdump -r` for manual inspection, not
//! just parseable by this crate's own reader — while still being decoded
//! and checked byte-for-byte without spinning up a live peer process, per
//! `ROADMAP.md`'s stated purpose for this deliverable ("so wire-format
//! regressions are caught without needing a live peer process in every CI
//! run").
//!
//! # Fixture provenance
//!
//! `tests/fixtures/rtps_go_dds_reference.pcap` is generated by
//! `examples/generate_rtps_pcap_fixture.rs` (run via `cargo run --example
//! generate_rtps_pcap_fixture > tests/fixtures/rtps_go_dds_reference.pcap`
//! from the repository root) from RTPS message bytes that are themselves
//! go-DDS's own real encoder output — every byte sequence the generator
//! uses is one this crate's earlier Tier 1 sub-phases already
//! independently verified byte-for-byte against go-DDS's actual
//! `buildParticipantData`/`buildEndpointData`/`marshalDataSubmessage`/
//! `marshalHeartbeat`/`marshalAckNack`/`marshalGAP`/`wrapInRTPSMessage`
//! functions (never reimplemented) via a package-local scratch Go test
//! file, run and deleted, never committed to go-DDS — see
//! `spdp.rs::tests::full_spdp_announcement_matches_go_dds_reference`,
//! `sedp.rs::tests::full_sedp_pub_announcement_matches_go_dds_reference`,
//! `participant.rs::tests::write_wire_message_matches_go_dds_reference`,
//! and `message.rs::tests::encode_heartbeat_submessage_matches_go_dds_reference`/
//! `encode_acknack_submessage_matches_go_dds_reference`/
//! `encode_gap_submessage_matches_go_dds_reference` for each one's own
//! doc-commented go-DDS reproduction command — this module does not
//! re-derive them. `generate_rtps_pcap_fixture.rs`'s own doc comment lists
//! the exact hex literal (and originating test) reused for each of the
//! fixture's seven recorded messages (SPDP announcement, SEDP publication
//! + subscription announcements, plain DATA, HEARTBEAT, ACKNACK, GAP).
//!
//! # Container format, precisely
//!
//! Each recorded RTPS message is wrapped in a synthetic (but wire-valid)
//! IPv4 header (20 bytes, no options, protocol 17/UDP, zero checksum —
//! legal for IPv4 per RFC 768 §"the sender's checksum need not be
//! computed") and UDP header (8 bytes, zero checksum, same legality) from
//! a fixed loopback source/destination (`127.0.0.1`, ports matching each
//! message's already-established reference config —
//! `17410`/`17411`, the same fixed ports `spdp.rs`/`sedp.rs`/
//! `participant.rs`'s own reference-vector tests already use). The pcap
//! global header declares `LINKTYPE_RAW` (DLT 101, "raw IP, no link
//! layer") — the simplest link type that keeps a real Ethernet/loopback
//! frame header out of scope while still producing a file real pcap
//! tooling parses correctly (`tcpdump -r <file>` with no `-y`/`-T` flags
//! needed).
//!
//! No `unsafe` anywhere (REQ-ASIL-002/REQ-MEM-001) and no panics on
//! malformed/truncated input (REQ-ASIL-003): [`decode_pcap_file`] returns
//! `Err(PcapError)`, never indexes out of bounds or unwraps.
//!
//! Internal only: not re-exported from the crate root.

use std::net::Ipv4Addr;

use thiserror::Error;

/// Decode error for the pcap container format (distinct from
/// [`super::RtpsDecodeError`], which is specific to RTPS wire types — a
/// malformed pcap *container* is a different failure mode than a
/// malformed RTPS *message*, and [`decode_pcap_file`] never attempts to
/// decode the RTPS payload itself, only to extract it).
//fusa:req REQ-RTPS-058
#[derive(Clone, Copy, Debug, PartialEq, Eq, Error)]
pub enum PcapError {
    /// Input shorter than required at this parse position.
    #[error("pcap: truncated input: expected at least {expected} bytes, got {got}")]
    Truncated { expected: usize, got: usize },
    /// Global header's magic number did not match the little-endian
    /// microsecond-resolution pcap magic (`0xa1b2c3d4`) this module always
    /// writes and is the only byte order/resolution it reads back.
    #[error("pcap: bad global-header magic: expected 0xa1b2c3d4, got 0x{got:08x}")]
    BadMagic { got: u32 },
    /// Global header's `network` (link-layer type) field was not
    /// `LINKTYPE_RAW` (101), the only link type this module produces/reads.
    #[error("pcap: unsupported link type: expected 101 (LINKTYPE_RAW), got {got}")]
    UnsupportedLinkType { got: u32 },
    /// A packet record's captured bytes did not decode as an IPv4/UDP
    /// datagram (version nibble != 4, protocol != 17, or a length field
    /// inconsistent with the record's declared `incl_len`).
    #[error("pcap: packet record {index} is not a well-formed IPv4/UDP datagram")]
    NotIpv4Udp { index: usize },
}

/// The libpcap magic number for a little-endian, microsecond-resolution
/// classic pcap file (as opposed to the big-endian or nanosecond-resolution
/// variants this module deliberately does not support — one fixed variant
/// is sufficient for a fixture this crate both writes and reads).
const PCAP_MAGIC_MICROS_LE: u32 = 0xa1b2_c3d4;

/// `LINKTYPE_RAW` — raw IP, no link-layer header. See the module docs'
/// "Container format, precisely" section for why this module uses it.
const LINKTYPE_RAW: u32 = 101;

const GLOBAL_HEADER_LEN: usize = 24;
const RECORD_HEADER_LEN: usize = 16;
const IPV4_HEADER_LEN: usize = 20;
const UDP_HEADER_LEN: usize = 8;
const IPPROTO_UDP: u8 = 17;

/// One recorded RTPS message, addressed and timestamped as if captured on
/// the wire. Every field except `payload` only exists to make the pcap
/// container a valid, inspectable IPv4/UDP capture — this crate's own
/// `Header::decode`/`SubmessageIter` (see `message.rs`) operate on
/// `payload` alone, exactly as they would on a live `RtpsDatagram`'s
/// `data` (see `transport.rs`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PcapPacket {
    pub ts_sec: u32,
    pub ts_usec: u32,
    pub src_addr: Ipv4Addr,
    pub src_port: u16,
    pub dst_addr: Ipv4Addr,
    pub dst_port: u16,
    /// The recorded RTPS message bytes (starting with the `"RTPS"` magic —
    /// see `message.rs::Header`), i.e. the UDP payload.
    pub payload: Vec<u8>,
}

// ---------------------------------------------------------------------------
// Encode
// ---------------------------------------------------------------------------

/// Encodes `packets` as a complete classic-format pcap file: one global
/// header followed by one packet record (16-byte record header + a
/// synthetic IPv4 header + a synthetic UDP header + `payload`) per entry.
/// Pure — never fails (every `PcapPacket` is representable; a `payload`
/// long enough to overflow `u16`'s UDP-length field is not a case this
/// fixture generator ever produces).
pub fn encode_pcap_file(packets: &[PcapPacket]) -> Vec<u8> {
    let mut out = Vec::with_capacity(GLOBAL_HEADER_LEN + packets.len() * 64);

    // Global header (RFC-less but universally implemented "classic pcap"
    // layout): magic, version_major, version_minor, thiszone, sigfigs,
    // snaplen, network — six further u32/u16 fields after the magic,
    // little-endian throughout to match PCAP_MAGIC_MICROS_LE.
    out.extend_from_slice(&PCAP_MAGIC_MICROS_LE.to_le_bytes());
    out.extend_from_slice(&2u16.to_le_bytes()); // version_major
    out.extend_from_slice(&4u16.to_le_bytes()); // version_minor
    out.extend_from_slice(&0i32.to_le_bytes()); // thiszone
    out.extend_from_slice(&0u32.to_le_bytes()); // sigfigs
    out.extend_from_slice(&65535u32.to_le_bytes()); // snaplen
    out.extend_from_slice(&LINKTYPE_RAW.to_le_bytes()); // network

    for pkt in packets {
        let udp_len = UDP_HEADER_LEN + pkt.payload.len();
        let ip_total_len = IPV4_HEADER_LEN + udp_len;

        let mut ip_udp_and_payload = Vec::with_capacity(ip_total_len);
        // IPv4 header, no options: version/IHL, DSCP/ECN, total length,
        // identification, flags/fragment offset, TTL, protocol, checksum
        // (zero — this module never validates it), source, destination.
        ip_udp_and_payload.push(0x45); // version=4, IHL=5 (20 bytes, no options)
        ip_udp_and_payload.push(0x00); // DSCP/ECN
        ip_udp_and_payload.extend_from_slice(&(ip_total_len as u16).to_be_bytes());
        ip_udp_and_payload.extend_from_slice(&0u16.to_be_bytes()); // identification
        ip_udp_and_payload.extend_from_slice(&0u16.to_be_bytes()); // flags/frag offset
        ip_udp_and_payload.push(64); // TTL
        ip_udp_and_payload.push(IPPROTO_UDP);
        ip_udp_and_payload.extend_from_slice(&0u16.to_be_bytes()); // header checksum
        ip_udp_and_payload.extend_from_slice(&pkt.src_addr.octets());
        ip_udp_and_payload.extend_from_slice(&pkt.dst_addr.octets());

        // UDP header: source port, destination port, length, checksum
        // (zero = not computed, legal for IPv4 per RFC 768).
        ip_udp_and_payload.extend_from_slice(&pkt.src_port.to_be_bytes());
        ip_udp_and_payload.extend_from_slice(&pkt.dst_port.to_be_bytes());
        ip_udp_and_payload.extend_from_slice(&(udp_len as u16).to_be_bytes());
        ip_udp_and_payload.extend_from_slice(&0u16.to_be_bytes());

        ip_udp_and_payload.extend_from_slice(&pkt.payload);

        let incl_len = ip_udp_and_payload.len() as u32;
        out.extend_from_slice(&pkt.ts_sec.to_le_bytes());
        out.extend_from_slice(&pkt.ts_usec.to_le_bytes());
        out.extend_from_slice(&incl_len.to_le_bytes());
        out.extend_from_slice(&incl_len.to_le_bytes()); // orig_len == incl_len: never truncated
        out.extend_from_slice(&ip_udp_and_payload);
    }

    out
}

// ---------------------------------------------------------------------------
// Decode
// ---------------------------------------------------------------------------

/// Decodes a complete pcap file produced by [`encode_pcap_file`] (or any
/// other little-endian, microsecond-resolution, `LINKTYPE_RAW` classic
/// pcap file wrapping IPv4/UDP datagrams with no IP options) back into its
/// [`PcapPacket`] records, in file order.
///
/// Never panics on malformed/truncated input — every bounds check returns
/// `Err(PcapError)` instead of indexing out of range or unwrapping
/// (REQ-ASIL-003).
//fusa:req REQ-RTPS-058
//fusa:req REQ-RTPS-009
pub fn decode_pcap_file(bytes: &[u8]) -> Result<Vec<PcapPacket>, PcapError> {
    if bytes.len() < GLOBAL_HEADER_LEN {
        return Err(PcapError::Truncated {
            expected: GLOBAL_HEADER_LEN,
            got: bytes.len(),
        });
    }
    let magic = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
    if magic != PCAP_MAGIC_MICROS_LE {
        return Err(PcapError::BadMagic { got: magic });
    }
    let network = u32::from_le_bytes([bytes[20], bytes[21], bytes[22], bytes[23]]);
    if network != LINKTYPE_RAW {
        return Err(PcapError::UnsupportedLinkType { got: network });
    }

    let mut packets = Vec::new();
    let mut pos = GLOBAL_HEADER_LEN;
    let mut index = 0usize;
    while pos < bytes.len() {
        let Some(record_header) = bytes.get(pos..pos + RECORD_HEADER_LEN) else {
            return Err(PcapError::Truncated {
                expected: pos + RECORD_HEADER_LEN,
                got: bytes.len(),
            });
        };
        let ts_sec = u32::from_le_bytes(record_header[0..4].try_into().unwrap());
        let ts_usec = u32::from_le_bytes(record_header[4..8].try_into().unwrap());
        let incl_len = u32::from_le_bytes(record_header[8..12].try_into().unwrap()) as usize;
        pos += RECORD_HEADER_LEN;

        let Some(record_data) = bytes.get(pos..pos + incl_len) else {
            return Err(PcapError::Truncated {
                expected: pos + incl_len,
                got: bytes.len(),
            });
        };
        pos += incl_len;

        packets.push(decode_ipv4_udp_record(record_data, ts_sec, ts_usec, index)?);
        index += 1;
    }
    Ok(packets)
}

fn decode_ipv4_udp_record(
    data: &[u8],
    ts_sec: u32,
    ts_usec: u32,
    index: usize,
) -> Result<PcapPacket, PcapError> {
    if data.len() < IPV4_HEADER_LEN + UDP_HEADER_LEN {
        return Err(PcapError::NotIpv4Udp { index });
    }
    let version_ihl = data[0];
    let ihl_words = version_ihl & 0x0f;
    let ihl_bytes = usize::from(ihl_words) * 4;
    if version_ihl >> 4 != 4 || ihl_bytes < IPV4_HEADER_LEN || data.len() < ihl_bytes {
        return Err(PcapError::NotIpv4Udp { index });
    }
    let protocol = data[9];
    if protocol != IPPROTO_UDP {
        return Err(PcapError::NotIpv4Udp { index });
    }
    let src_addr = Ipv4Addr::new(data[12], data[13], data[14], data[15]);
    let dst_addr = Ipv4Addr::new(data[16], data[17], data[18], data[19]);

    let Some(udp) = data.get(ihl_bytes..ihl_bytes + UDP_HEADER_LEN) else {
        return Err(PcapError::NotIpv4Udp { index });
    };
    let src_port = u16::from_be_bytes([udp[0], udp[1]]);
    let dst_port = u16::from_be_bytes([udp[2], udp[3]]);
    let udp_len = usize::from(u16::from_be_bytes([udp[4], udp[5]]));
    if udp_len < UDP_HEADER_LEN {
        return Err(PcapError::NotIpv4Udp { index });
    }
    let payload_len = udp_len - UDP_HEADER_LEN;
    let payload_start = ihl_bytes + UDP_HEADER_LEN;
    let Some(payload) = data.get(payload_start..payload_start + payload_len) else {
        return Err(PcapError::NotIpv4Udp { index });
    };

    Ok(PcapPacket {
        ts_sec,
        ts_usec,
        src_addr,
        src_port,
        dst_addr,
        dst_port,
        payload: payload.to_vec(),
    })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_packet(payload: Vec<u8>, src_port: u16, dst_port: u16) -> PcapPacket {
        PcapPacket {
            ts_sec: 1_700_000_000,
            ts_usec: 0,
            src_addr: Ipv4Addr::new(127, 0, 0, 1),
            src_port,
            dst_addr: Ipv4Addr::new(127, 0, 0, 1),
            dst_port,
            payload,
        }
    }

    //fusa:test REQ-RTPS-058
    #[test]
    fn encode_then_decode_round_trips_one_packet() {
        let pkt = sample_packet(vec![0xDE, 0xAD, 0xBE, 0xEF], 17410, 17411);
        let bytes = encode_pcap_file(std::slice::from_ref(&pkt));
        let decoded = decode_pcap_file(&bytes).unwrap();
        assert_eq!(decoded, vec![pkt]);
    }

    //fusa:test REQ-RTPS-058
    #[test]
    fn encode_then_decode_round_trips_several_packets_in_order() {
        let pkts = vec![
            sample_packet(vec![0x01; 8], 17410, 17411),
            sample_packet(vec![0x02; 3], 27410, 27411),
            sample_packet(vec![], 100, 200), // empty payload is still valid
        ];
        let bytes = encode_pcap_file(&pkts);
        let decoded = decode_pcap_file(&bytes).unwrap();
        assert_eq!(decoded, pkts);
    }

    //fusa:test REQ-RTPS-058
    #[test]
    fn global_header_matches_expected_layout() {
        let bytes = encode_pcap_file(&[]);
        assert_eq!(bytes.len(), GLOBAL_HEADER_LEN);
        assert_eq!(&bytes[0..4], &PCAP_MAGIC_MICROS_LE.to_le_bytes());
        assert_eq!(&bytes[20..24], &LINKTYPE_RAW.to_le_bytes());
    }

    //fusa:test REQ-RTPS-058
    //fusa:test REQ-RTPS-009
    #[test]
    fn decode_rejects_truncated_global_header_without_panicking() {
        assert_eq!(
            decode_pcap_file(&[0u8; 10]),
            Err(PcapError::Truncated {
                expected: GLOBAL_HEADER_LEN,
                got: 10
            })
        );
    }

    //fusa:test REQ-RTPS-058
    //fusa:test REQ-RTPS-009
    #[test]
    fn decode_rejects_bad_magic_without_panicking() {
        let mut bytes = encode_pcap_file(&[]);
        bytes[0] = 0x00;
        assert_eq!(
            decode_pcap_file(&bytes),
            Err(PcapError::BadMagic { got: 0xa1b2c300 })
        );
    }

    //fusa:test REQ-RTPS-058
    //fusa:test REQ-RTPS-009
    #[test]
    fn decode_rejects_truncated_packet_record_without_panicking() {
        let pkt = sample_packet(vec![0xAA; 4], 1, 2);
        let mut bytes = encode_pcap_file(std::slice::from_ref(&pkt));
        bytes.truncate(bytes.len() - 2); // chop the last 2 payload bytes off
        assert!(matches!(
            decode_pcap_file(&bytes),
            Err(PcapError::Truncated { .. })
        ));
    }

    //fusa:test REQ-RTPS-058
    //fusa:test REQ-RTPS-009
    #[test]
    fn decode_rejects_non_ipv4_udp_record_without_panicking() {
        // A well-formed global header followed by one record whose "IPv4"
        // header claims IPv6 (version nibble 6) instead.
        let mut bytes = encode_pcap_file(&[]);
        let mut bogus_record = vec![0x65u8]; // version=6, not 4
        bogus_record.resize(IPV4_HEADER_LEN + UDP_HEADER_LEN, 0);
        let incl_len = bogus_record.len() as u32;
        bytes.extend_from_slice(&0u32.to_le_bytes()); // ts_sec
        bytes.extend_from_slice(&0u32.to_le_bytes()); // ts_usec
        bytes.extend_from_slice(&incl_len.to_le_bytes());
        bytes.extend_from_slice(&incl_len.to_le_bytes());
        bytes.extend_from_slice(&bogus_record);
        assert_eq!(
            decode_pcap_file(&bytes),
            Err(PcapError::NotIpv4Udp { index: 0 })
        );
    }
}
